/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alega
 */
public class Cobro extends javax.swing.JDialog {

    /**
     * Creates new form Cobro
     */
    public Cobro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subotal = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        totalTxt1 = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        total2 = new javax.swing.JTextField();
        totalTxt2 = new javax.swing.JTextField();
        ticketBoton = new javax.swing.JButton();
        facturaBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        subotal.setEditable(false);
        subotal.setBackground(new java.awt.Color(51, 51, 51));
        subotal.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        subotal.setForeground(new java.awt.Color(204, 204, 204));
        subotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subotal.setText("COBRO DE PRODUCTOS");
        subotal.setBorder(null);
        subotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subotalActionPerformed(evt);
            }
        });

        totalTxt.setEditable(false);
        totalTxt.setBackground(new java.awt.Color(51, 51, 51));
        totalTxt.setForeground(new java.awt.Color(204, 204, 204));

        total.setEditable(false);
        total.setBackground(new java.awt.Color(51, 51, 51));
        total.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(204, 204, 204));
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("Total");
        total.setBorder(null);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        totalTxt1.setEditable(false);
        totalTxt1.setBackground(new java.awt.Color(51, 51, 51));
        totalTxt1.setForeground(new java.awt.Color(204, 204, 204));

        total1.setEditable(false);
        total1.setBackground(new java.awt.Color(51, 51, 51));
        total1.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        total1.setForeground(new java.awt.Color(204, 204, 204));
        total1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total1.setText("Efectivo");
        total1.setBorder(null);
        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });

        total2.setEditable(false);
        total2.setBackground(new java.awt.Color(51, 51, 51));
        total2.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        total2.setForeground(new java.awt.Color(204, 204, 204));
        total2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total2.setText("Cambio");
        total2.setBorder(null);
        total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total2ActionPerformed(evt);
            }
        });

        totalTxt2.setEditable(false);
        totalTxt2.setBackground(new java.awt.Color(51, 51, 51));
        totalTxt2.setForeground(new java.awt.Color(204, 204, 204));

        ticketBoton.setBackground(new java.awt.Color(51, 51, 51));
        ticketBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        ticketBoton.setForeground(new java.awt.Color(0, 0, 0));
        ticketBoton.setText("Ticket");
        ticketBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ticketBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketBotonActionPerformed(evt);
            }
        });

        facturaBoton.setBackground(new java.awt.Color(51, 51, 51));
        facturaBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        facturaBoton.setForeground(new java.awt.Color(0, 0, 0));
        facturaBoton.setText("Factura");
        facturaBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        facturaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(subotal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ticketBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(facturaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(subotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facturaBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facturaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaBotonActionPerformed

    }//GEN-LAST:event_facturaBotonActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void subotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subotalActionPerformed

    private void ticketBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketBotonActionPerformed
        // TODO add your handling code here

        }

        private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here
    }//GEN-LAST:event_ticketBotonActionPerformed

    private void total2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total2ActionPerformed

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cobro dialog = new Cobro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton facturaBoton;
    private javax.swing.JTextField subotal;
    private javax.swing.JButton ticketBoton;
    private javax.swing.JTextField total;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JTextField totalTxt1;
    private javax.swing.JTextField totalTxt2;
    // End of variables declaration//GEN-END:variables
}
