/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.EmpleadoJpaController;
import control.exceptions.NonexistentEntityException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author alega
 */
public class EmpleadoVista extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadoVista
     */
    
    private EntityManagerFactory emf;
    Empleado empleado;
    EmpleadoJpaController ec;
    private String estado = null;
    
    public EmpleadoVista() {
        initComponents();
        setLocationRelativeTo(null);
        calendarioMethod();
        noVisualizar();
        inicio();
    }
    
    public void noVisualizar(){
        buscarBoton.setVisible(false);
        nombreLabel.setVisible(false);
        nombreCombo.setVisible(false);
        idEmpleadoTxt.setVisible(false);
        idEmpleadoLabel.setVisible(false);
    }
    
    public void iniciarControlador(){
        emf = Persistence.createEntityManagerFactory("NanoSystemPU");
        ec = new EmpleadoJpaController(emf);
    }
    
    public void calendarioMethod(){
        Calendar calendario1 = new GregorianCalendar();
        int año = calendario1.getWeekYear()-18;
        Date date = new Date();
        calendario1.set(año,date.getMonth(),date.getDate());
        calendario.setMaxDate(calendario1);
        calendario.setSelectedDate(calendario1);
    }
    
    public void inicio (){
        aceptarBoton.setVisible(false);
        cancelarBoton.setVisible(false);
        
        nombreTxt.setEditable(false);
        turnoTxt.setEditable(false);
        calendarioAux.setEditable(false);
        fechaContratacionTxt.setEditable(false);
        calendarioAux.setVisible(true);
        calendario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        NanoSystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("NanoSystemPU").createEntityManager();
        empleadoQuery = java.beans.Beans.isDesignTime() ? null : NanoSystemPUEntityManager.createQuery("SELECT e FROM Empleado e");
        empleadoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : empleadoQuery.getResultList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        turnoTxt = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        calendarioAux = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        aceptarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();
        calendario = new datechooser.beans.DateChooserCombo();
        fechaContratacionTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        idEmpleadoLabel = new javax.swing.JLabel();
        idEmpleadoTxt = new javax.swing.JTextField();
        buscarBoton = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        nombreCombo = new javax.swing.JComboBox();
        agregarBoton = new javax.swing.JButton();
        agregarBoton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        agregarBoton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/font.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 900));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("EMPLEADO");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 51, 59));
        jTextField3.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText(" Nombre");
        jTextField3.setBorder(null);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 66, 70, 27));

        nombreTxt.setBackground(new java.awt.Color(51, 51, 51));
        nombreTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(204, 204, 204));
        nombreTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 62, 210, 36));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(51, 51, 59));
        jTextField6.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setText(" Turno");
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 143, 70, 27));

        turnoTxt.setBackground(new java.awt.Color(51, 51, 51));
        turnoTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        turnoTxt.setForeground(new java.awt.Color(204, 204, 204));
        turnoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(turnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 139, 210, 36));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(51, 51, 59));
        jTextField8.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.setText(" Fecha de Contratación");
        jTextField8.setBorder(null);
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 217, 205, 27));

        calendarioAux.setBackground(new java.awt.Color(51, 51, 51));
        calendarioAux.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        calendarioAux.setForeground(new java.awt.Color(204, 204, 204));
        calendarioAux.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(calendarioAux, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 228, 36));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(51, 51, 59));
        jTextField10.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(0, 0, 0));
        jTextField10.setText(" Fecha de Nacimiento");
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 343, -1, 27));

        aceptarBoton.setBackground(new java.awt.Color(51, 51, 51));
        aceptarBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        aceptarBoton.setForeground(new java.awt.Color(0, 0, 0));
        aceptarBoton.setText("Aceptar");
        aceptarBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 40));

        cancelarBoton.setBackground(new java.awt.Color(51, 51, 51));
        cancelarBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        cancelarBoton.setForeground(new java.awt.Color(0, 0, 0));
        cancelarBoton.setText("Cancelar");
        cancelarBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 110, 40));

        calendario.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    calendario.setCalendarPreferredSize(new java.awt.Dimension(350, 200));
    calendario.setFormat(0);
    calendario.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
    calendario.setFieldFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 15));
    calendario.setNavigateFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12));
    calendario.setShowOneMonth(true);
    jPanel1.add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 382, 230, 30));

    fechaContratacionTxt.setBackground(new java.awt.Color(51, 51, 51));
    fechaContratacionTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
    fechaContratacionTxt.setForeground(new java.awt.Color(204, 204, 204));
    fechaContratacionTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel1.add(fechaContratacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 262, 228, 36));

    jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 370, 530));

    org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, empleadoList, tablaEmpleado);
    org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idEmpleado}"));
    columnBinding.setColumnName("Id Empleado");
    columnBinding.setColumnClass(Integer.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
    columnBinding.setColumnName("Nombre");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${turno}"));
    columnBinding.setColumnName("Turno");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaContratacion}"));
    columnBinding.setColumnName("Fecha Contratacion");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaNacimiento}"));
    columnBinding.setColumnName("Fecha Nacimiento");
    columnBinding.setColumnClass(java.util.Date.class);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();
    tablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            listenerTablaEmpleado(evt);
        }
    });
    jScrollPane1.setViewportView(tablaEmpleado);

    jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 740, 320));

    idEmpleadoLabel.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
    idEmpleadoLabel.setForeground(new java.awt.Color(204, 204, 204));
    idEmpleadoLabel.setText("ID Empleado");
    jPanel2.add(idEmpleadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

    idEmpleadoTxt.setBackground(new java.awt.Color(51, 51, 51));
    idEmpleadoTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
    idEmpleadoTxt.setForeground(new java.awt.Color(204, 204, 204));
    jPanel2.add(idEmpleadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 140, -1));

    buscarBoton.setBackground(new java.awt.Color(51, 51, 51));
    buscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
    buscarBoton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buscarBotonActionPerformed(evt);
        }
    });
    jPanel2.add(buscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 30, 40));

    nombreLabel.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
    nombreLabel.setForeground(new java.awt.Color(204, 204, 204));
    nombreLabel.setText("Nombre del empleado");
    jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

    nombreCombo.setBackground(new java.awt.Color(51, 51, 51));
    nombreCombo.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
    nombreCombo.setForeground(new java.awt.Color(204, 204, 204));
    nombreCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Item 1", "Item 2", "Item 3", "Item 4" }));
    jPanel2.add(nombreCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 220, -1));

    agregarBoton.setBackground(new java.awt.Color(51, 51, 51));
    agregarBoton.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
    agregarBoton.setForeground(new java.awt.Color(0, 0, 0));
    agregarBoton.setText("Editar");
    agregarBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    agregarBoton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            agregarBotonActionPerformed(evt);
        }
    });
    jPanel2.add(agregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 80, 40));

    agregarBoton1.setBackground(new java.awt.Color(51, 51, 51));
    agregarBoton1.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
    agregarBoton1.setForeground(new java.awt.Color(0, 0, 0));
    agregarBoton1.setText("   Eliminar");
    agregarBoton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    agregarBoton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            agregarBoton1ActionPerformed(evt);
        }
    });
    jPanel2.add(agregarBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 110, 40));

    jButton1.setBackground(new java.awt.Color(51, 51, 51));
    jButton1.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
    jButton1.setForeground(new java.awt.Color(0, 0, 0));
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuprincipal.png"))); // NOI18N
    jButton1.setText("   Regresar al menú gerencia");
    jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 270, 50));

    agregarBoton3.setBackground(new java.awt.Color(51, 51, 51));
    agregarBoton3.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
    agregarBoton3.setForeground(new java.awt.Color(0, 0, 0));
    agregarBoton3.setText("Agregar");
    agregarBoton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    agregarBoton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            agregarBoton3ActionPerformed(evt);
        }
    });
    jPanel2.add(agregarBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 110, 40));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1240, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 599, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NavegacionGerencia ng = new NavegacionGerencia();
        ng.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listenerTablaEmpleado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listenerTablaEmpleado
        // TODO add your handling code here:
        int idEmp = tablaEmpleado.getSelectedRow();
        calendarioAux.setVisible(true);
        nombreTxt.setText(tablaEmpleado.getValueAt(idEmp,1).toString());
        turnoTxt.setText(tablaEmpleado.getValueAt(idEmp,2).toString());
        calendarioAux.setText(tablaEmpleado.getValueAt(idEmp,4).toString());
        fechaContratacionTxt.setText(tablaEmpleado.getValueAt(idEmp,3).toString());
        
    }//GEN-LAST:event_listenerTablaEmpleado

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        // TODO add your handling code here:
        if(tablaEmpleado.getSelectedRow()>0){
            aceptarBoton.setVisible(true);
            cancelarBoton.setVisible(true);
            nombreTxt.setEditable(true);
            turnoTxt.setEditable(true);
            estado = "editar";
        }
        else
            JOptionPane.showMessageDialog(null,"Primero seleccione un empleado");
    }//GEN-LAST:event_agregarBotonActionPerformed

    public void actualizarTabla(){
        this.setVisible(false);
        EmpleadoVista empAux = new EmpleadoVista();
        empAux.setVisible(true);
    }
    
    private void agregarBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBoton1ActionPerformed
        // TODO add your handling code here:
        int fila = tablaEmpleado.getSelectedRow();
        if(fila>0){
            
            aceptarBoton.setVisible(false);
            cancelarBoton.setVisible(false);
            nombreTxt.setEditable(false);
            turnoTxt.setEditable(false);
            if(JOptionPane.showConfirmDialog(null,"¿Está seguro que desea eliminar al empleado "+tablaEmpleado.getValueAt(fila, 1)+"?","",JOptionPane.YES_NO_OPTION)==0){
                JOptionPane.showMessageDialog(null,tablaEmpleado.getValueAt(fila, 1) + " eliminado");
                iniciarControlador();
                try {
                    ec.destroy(Integer.parseInt(tablaEmpleado.getValueAt(fila,0).toString()));
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                }
                actualizarTabla();
            } 
        }
        else
            JOptionPane.showMessageDialog(null,"Primero seleccione un empleado");
        
    }//GEN-LAST:event_agregarBoton1ActionPerformed

    private void agregarBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBoton3ActionPerformed
        // TODO add your handling code here:
            Date date = new Date();
            nombreTxt.setEditable(true);
            turnoTxt.setEditable(true);
            
            nombreTxt.setText(null);
            turnoTxt.setText(null);
            fechaContratacionTxt.setText(date.toLocaleString());
            calendarioAux.setVisible(false);
            calendario.setVisible(true);
            
            aceptarBoton.setVisible(true);
            cancelarBoton.setVisible(true);
        
            estado = "agregar";
    }//GEN-LAST:event_agregarBoton3ActionPerformed

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        // TODO add your handling code here:
        inicio();
        turnoTxt.setText(null);
        nombreTxt.setText(null);
        calendarioAux.setText(null);
        fechaContratacionTxt.setText(null);
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        // TODO add your handling code here:
        if(estado.equals("agregar")){
            Date date = new Date();
            empleado = new Empleado();
            empleado.setNombre(nombreTxt.getText());
            empleado.setTurno(turnoTxt.getText());
            empleado.setFechaContratacion(date);
            empleado.setFechaNacimiento(calendario.getCurrent().getTime());
            
            iniciarControlador();
            ec.create(empleado);
            JOptionPane.showMessageDialog(null,"Empleado "+nombreTxt.getText()+" agregado correctamente");
            actualizarTabla();
        }
        else if (estado.equals("editar")){
            int id = Integer.parseInt(tablaEmpleado.getValueAt(tablaEmpleado.getSelectedRow(),0).toString());
            
            iniciarControlador();
            empleado= ec.findEmpleado(id);
            empleado.setNombre(nombreTxt.getText());
            empleado.setTurno(turnoTxt.getText());
            try {
                ec.edit(empleado);
            } catch (Exception ex) {
                Logger.getLogger(EmpleadoVista.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(null,"Empleado "+nombreTxt.getText()+" actualizado correctamente");
            actualizarTabla();        
        }
        
        aceptarBoton.setVisible(false);
        cancelarBoton.setVisible(false);
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager NanoSystemPUEntityManager;
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JButton agregarBoton;
    private javax.swing.JButton agregarBoton1;
    private javax.swing.JButton agregarBoton3;
    private javax.swing.JButton buscarBoton;
    private datechooser.beans.DateChooserCombo calendario;
    private javax.swing.JTextField calendarioAux;
    private javax.swing.JButton cancelarBoton;
    private java.util.List<modelo.Empleado> empleadoList;
    private javax.persistence.Query empleadoQuery;
    private javax.swing.JTextField fechaContratacionTxt;
    private javax.swing.JLabel idEmpleadoLabel;
    private javax.swing.JTextField idEmpleadoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JComboBox nombreCombo;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField turnoTxt;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
