/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

//import com.itextpdf.kernel.geom.PageSize;
//import com.itextpdf.kernel.pdf.PdfDocument;
//import com.itextpdf.kernel.pdf.PdfDocument;
//import com.itextpdf.kernel.pdf.PdfWriter;
//import com.itextpdf.layout.Document;
//import com.itextpdf.layout.element.Paragraph;
import java.io.FileNotFoundException;
/**
 *
 * @author alega
 */
public class Factura extends javax.swing.JFrame {

    
    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void generarpdf() throws FileNotFoundException{
 //       Document document = new Document(PageSize.A4.applyMargins(35, 30, 50, 50, rootPaneCheckingEnabled));
//        PdfWriter writer = new PdfWriter("PDFS");
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calle = new javax.swing.JTextField();
        nombreEmpresa = new javax.swing.JTextField();
        numeroExt = new javax.swing.JTextField();
        numeroint = new javax.swing.JTextField();
        colonia = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        codigoPostal = new javax.swing.JTextField();
        rfc = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Pago = new javax.swing.JComboBox<>();
        tipoServicio1 = new javax.swing.JTextField();
        subTotal = new javax.swing.JTextField();
        iva = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturación Nano System");

        jPanel1.setBackground(new java.awt.Color(6, 34, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calle.setBackground(new java.awt.Color(51, 51, 51));
        calle.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        calle.setForeground(new java.awt.Color(204, 204, 204));
        calle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        calle.setText("Calle");
        calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleActionPerformed(evt);
            }
        });
        jPanel1.add(calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 216, -1));

        nombreEmpresa.setBackground(new java.awt.Color(51, 51, 51));
        nombreEmpresa.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(204, 204, 204));
        nombreEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreEmpresa.setText("Nombre empresa");
        nombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(nombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 229, -1));

        numeroExt.setBackground(new java.awt.Color(51, 51, 51));
        numeroExt.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        numeroExt.setForeground(new java.awt.Color(204, 204, 204));
        numeroExt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroExt.setText("Numero ext");
        numeroExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroExtActionPerformed(evt);
            }
        });
        jPanel1.add(numeroExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        numeroint.setBackground(new java.awt.Color(51, 51, 51));
        numeroint.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        numeroint.setForeground(new java.awt.Color(204, 204, 204));
        numeroint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroint.setText("Numero int");
        numeroint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerointActionPerformed(evt);
            }
        });
        jPanel1.add(numeroint, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 121, -1));

        colonia.setBackground(new java.awt.Color(51, 51, 51));
        colonia.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        colonia.setForeground(new java.awt.Color(204, 204, 204));
        colonia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colonia.setText("Colonia");
        colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloniaActionPerformed(evt);
            }
        });
        jPanel1.add(colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 216, -1));

        ciudad.setBackground(new java.awt.Color(51, 51, 51));
        ciudad.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        ciudad.setForeground(new java.awt.Color(204, 204, 204));
        ciudad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ciudad.setText("Ciudad");
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });
        jPanel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 167, -1));

        codigoPostal.setBackground(new java.awt.Color(51, 51, 51));
        codigoPostal.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        codigoPostal.setForeground(new java.awt.Color(204, 204, 204));
        codigoPostal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoPostal.setText("Codigo postal");
        codigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPostalActionPerformed(evt);
            }
        });
        jPanel1.add(codigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 121, -1));

        rfc.setBackground(new java.awt.Color(51, 51, 51));
        rfc.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        rfc.setForeground(new java.awt.Color(204, 204, 204));
        rfc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rfc.setText("RFC");
        rfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfcActionPerformed(evt);
            }
        });
        jPanel1.add(rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 400, -1));

        total.setBackground(new java.awt.Color(51, 51, 51));
        total.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        total.setForeground(new java.awt.Color(204, 204, 204));
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 121, -1));

        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setText("Email");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 121, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nombre empresa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Calle:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 57, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Numero #:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Numero int:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("RFC:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 34, 28));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Colonia:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 57, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Ciudad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 57, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Codigo Postal:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Total:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 40, 20));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Forma de pago:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Email:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 54, -1));

        Pago.setBackground(new java.awt.Color(51, 51, 51));
        Pago.setForeground(new java.awt.Color(204, 204, 204));
        Pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de crédito" }));
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });
        jPanel1.add(Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 170, -1));

        tipoServicio1.setBackground(new java.awt.Color(51, 51, 51));
        tipoServicio1.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        tipoServicio1.setForeground(new java.awt.Color(204, 204, 204));
        tipoServicio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipoServicio1.setText("Tipo servicio");
        tipoServicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoServicio1ActionPerformed(evt);
            }
        });
        jPanel1.add(tipoServicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 121, -1));

        subTotal.setBackground(new java.awt.Color(51, 51, 51));
        subTotal.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        subTotal.setForeground(new java.awt.Color(204, 204, 204));
        subTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subTotal.setText("Sub total");
        subTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalActionPerformed(evt);
            }
        });
        jPanel1.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 121, -1));

        iva.setBackground(new java.awt.Color(51, 51, 51));
        iva.setFont(new java.awt.Font("Euphemia UCAS", 0, 14)); // NOI18N
        iva.setForeground(new java.awt.Color(204, 204, 204));
        iva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iva.setText("Iva");
        iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaActionPerformed(evt);
            }
        });
        jPanel1.add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 121, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Tipo de servicio:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Sub total:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 20));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Iva:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 40, 20));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        jButton2.setText("Eliminar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void rfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfcActionPerformed

    private void codigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPostalActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed

    private void coloniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coloniaActionPerformed

    private void numerointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerointActionPerformed

    private void numeroExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroExtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroExtActionPerformed

    private void nombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEmpresaActionPerformed

    private void calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleActionPerformed

    private void PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagoActionPerformed

    private void tipoServicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoServicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoServicio1ActionPerformed

    private void subTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalActionPerformed

    private void ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JComboBox<String> Pago;
    private javax.swing.JTextField calle;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField codigoPostal;
    private javax.swing.JTextField colonia;
    private javax.swing.JTextField email;
    private javax.swing.JTextField iva;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreEmpresa;
    private javax.swing.JTextField numeroExt;
    private javax.swing.JTextField numeroint;
    private javax.swing.JTextField rfc;
    private javax.swing.JTextField subTotal;
    private javax.swing.JTextField tipoServicio1;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
